### ISSUE TITLE
strict-aliasing

### ISSUE THREAD

**Issue by hasufell** [DDR0/Cube_Trains.bak#2]
- QA Notice: Package triggers severe warnings which indicate that it
-            may exhibit random runtime failures.
- src/md5.cpp:166:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
- src/md5.cpp:167:30: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

A shortcut to fix this would be "-fno-strict-aliasing", but it would be nicer to have this fixed in the code.

**Comment by DDR0** [comment]
OK, back from vacation. I think, to compile, you should use the -fno- thing for now. This game is based on the Frogatto engine, and the version here is a bit out-of-date. This bug maaaay be fixed in Frogatto, if so it'll be fixed here as well when the next release comes up.

Thanks for the feedback and all. :)

**Comment by DDR0** [comment]
The word from the original programmer is that we should use -fno-strict-aliasing. I believe it is intentionally this way, but I'm having a bit of difficulty getting through to him today.
